// The public, no-login intervention-request form. A sibling route group to
// (protected)/(auth) — see (auth)/login/page.tsx — with no auth-gating
// layout, so it's reachable by a customer who scans a QR code and has no
// RWCrew account at all. The QR code (generated by a separate,
// not-yet-built module) encodes a URL with query parameters that pre-fill
// Ploeg/Karnr/Afleverplaats/Zone; this page just reads them straight off
// searchParams and hands them to the form as defaults.

import { ServerApiError, serverApiFetch } from "@/lib/server-api";
import type { InterventionRequestsTeam } from "@/lib/types";
import { PublicInterventionRequestForm } from "@/components/module-3/public-intervention-request-form";

interface InterventionRequestPageProps {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

/** The first value of a query param, if it was given as a plain string —
 *  a QR-encoded URL never repeats a key, so a string[] here would mean a
 *  malformed link; treat that the same as "not provided". */
function firstParam(value: string | string[] | undefined): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

export default async function InterventionRequestPage({ searchParams }: InterventionRequestPageProps) {
  const params = await searchParams;

  const teams: InterventionRequestsTeam[] = await serverApiFetch<InterventionRequestsTeam[]>(
    "/api/public/intervention-requests/teams",
  ).catch((error) => {
    // The public form should still render (with the "other" free-text
    // Ploeg option) even if the teams lookup itself fails.
    if (error instanceof ServerApiError) return [];
    throw error;
  });

  const teamIdParam = firstParam(params.team_id);
  const parsedTeamId = teamIdParam ? Number(teamIdParam) : NaN;
  const matchingTeam = teams.find((team) => team.id === parsedTeamId);

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-4">
      <PublicInterventionRequestForm
        teams={teams}
        defaults={{
          team_id: matchingTeam?.id ?? null,
          team_name: firstParam(params.team_name) ?? null,
          cart_number: firstParam(params.cart_number) ?? null,
          delivery_location: firstParam(params.delivery_location) ?? null,
          zone: firstParam(params.zone) ?? null,
        }}
      />
    </div>
  );
}
