# The public, no-login entry point for Intervention Requests: customers
# reach this via a QR code (generated by a separate, not-yet-built module)
# that encodes a URL with query parameters pre-filling Ploeg/Karnr/
# Afleverplaats/Zone. Every endpoint here is deliberately free of
# get_current_user/require_module_access — modeled on app/landing/auth.py's
# login endpoint, the codebase's existing unauthenticated-endpoint pattern —
# unlike every endpoint in router.py, which is staff-only.

import heapq
from collections import defaultdict, deque
from threading import Lock
from time import monotonic

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.db.models.intervention_request import InterventionRequest
from app.db.models.team import Team
from app.modules.module_3.service import (
    generate_request_number,
    get_default_new_status,
    list_teams_for_dropdown,
)
from app.schemas.intervention_requests import (
    InterventionRequestResponse,
    InterventionRequestsTeamResponse,
    PublicInterventionRequestCreateRequest,
)

router = APIRouter(prefix="/api/public/intervention-requests", tags=["Intervention Requests (Public)"])

PUBLIC_REQUEST_RATE_LIMIT = 10
PUBLIC_REQUEST_RATE_WINDOW_SECONDS = 60.0
# Keep lock-held cleanup bounded even when many different IPs have used the
# public form since the last request.
PUBLIC_REQUEST_CLEANUP_MAX_REMOVALS = 32
_public_request_attempts: dict[str, deque[float]] = defaultdict(deque)
_public_request_expiries: list[tuple[float, str]] = []
_public_request_attempts_lock = Lock()


def _prune_expired_rate_limit_entries(now: float) -> None:
    """Evict at most a fixed number of expired queue entries.
    Must be called with _public_request_attempts_lock already held.
    """
    # Entries in the heap store an absolute expiry time (insertion time +
    # window), so they must be compared against the current time, not a
    # window-shifted cutoff - otherwise eviction lags a full window behind.
    cutoff = now - PUBLIC_REQUEST_RATE_WINDOW_SECONDS
    removals = 0
    while _public_request_expiries and _public_request_expiries[0][0] <= now:
        _, client_ip = heapq.heappop(_public_request_expiries)
        attempts = _public_request_attempts.get(client_ip)
        if attempts is None:
            continue
        while attempts and attempts[0] <= cutoff:
            attempts.popleft()
        if not attempts:
            del _public_request_attempts[client_ip]
        removals += 1
        if removals >= PUBLIC_REQUEST_CLEANUP_MAX_REMOVALS:
            break


def _enforce_public_request_rate_limit(request: Request) -> None:
    """Allow a small number of public submissions per client IP per minute."""
    client_ip = request.client.host if request.client is not None else "unknown"
    now = monotonic()
    cutoff = now - PUBLIC_REQUEST_RATE_WINDOW_SECONDS
    with _public_request_attempts_lock:
        _prune_expired_rate_limit_entries(now)

        attempts = _public_request_attempts[client_ip]
        while attempts and attempts[0] <= cutoff:
            attempts.popleft()
        if len(attempts) >= PUBLIC_REQUEST_RATE_LIMIT:
            raise HTTPException(status_code=status.HTTP_429_TOO_MANY_REQUESTS, detail="Too many requests")
        attempts.append(now)
        heapq.heappush(_public_request_expiries, (now + PUBLIC_REQUEST_RATE_WINDOW_SECONDS, client_ip))


@router.get("/teams", response_model=list[InterventionRequestsTeamResponse])
def list_public_teams(db: Session = Depends(get_db)) -> list[Team]:
    """Every MasterData team, for the public form's "Ploeg" dropdown."""
    return list_teams_for_dropdown(db)


@router.post("", response_model=InterventionRequestResponse, status_code=status.HTTP_201_CREATED)
def create_public_intervention_request(
    payload: PublicInterventionRequestCreateRequest,
    request: Request,
    db: Session = Depends(get_db),
) -> InterventionRequest:
    """Create a brand-new intervention request from the public form.

    Unlike the staff-only create_intervention_request in router.py, the
    caller can never choose status_id/handled_by/team_cart_user_id — those
    are internal-only fields, set here rather than trusted from an
    anonymous submitter.
    """
    _enforce_public_request_rate_limit(request)

    if payload.team_id is not None and db.get(Team, payload.team_id) is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Team not found")

    new_request = InterventionRequest(
        request_number=generate_request_number(db),
        status_id=get_default_new_status(db).id,
        handled_by=None,
        team_cart_user_id=None,
        **payload.model_dump(),
    )
    db.add(new_request)
    db.commit()
    db.refresh(new_request)
    return new_request
