# The public, no-login entry point for Intervention Requests: customers
# reach this via a QR code (generated by a separate, not-yet-built module)
# that encodes a URL with query parameters pre-filling Ploeg/Karnr/
# Afleverplaats/Zone. Every endpoint here is deliberately free of
# get_current_user/require_module_access — modeled on app/landing/auth.py's
# login endpoint, the codebase's existing unauthenticated-endpoint pattern —
# unlike every endpoint in router.py, which is staff-only.

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.db.models.intervention_request import InterventionRequest
from app.db.models.team import Team
from app.modules.module_3.service import (
    generate_request_number,
    get_default_new_status,
    list_teams_for_dropdown,
)
from app.schemas.intervention_requests import (
    InterventionRequestResponse,
    InterventionRequestsTeamResponse,
    PublicInterventionRequestCreateRequest,
)

router = APIRouter(prefix="/api/public/intervention-requests", tags=["Intervention Requests (Public)"])


@router.get("/teams", response_model=list[InterventionRequestsTeamResponse])
def list_public_teams(db: Session = Depends(get_db)) -> list[Team]:
    """Every MasterData team, for the public form's "Ploeg" dropdown."""
    return list_teams_for_dropdown(db)


@router.post("", response_model=InterventionRequestResponse, status_code=status.HTTP_201_CREATED)
def create_public_intervention_request(
    payload: PublicInterventionRequestCreateRequest,
    db: Session = Depends(get_db),
) -> InterventionRequest:
    """Create a brand-new intervention request from the public form.

    Unlike the staff-only create_intervention_request in router.py, the
    caller can never choose status_id/handled_by/team_cart_user_id — those
    are internal-only fields, set here rather than trusted from an
    anonymous submitter.
    """
    if payload.team_id is not None and db.get(Team, payload.team_id) is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Team not found")

    new_request = InterventionRequest(
        request_number=generate_request_number(db),
        status_id=get_default_new_status(db).id,
        handled_by=None,
        team_cart_user_id=None,
        **payload.model_dump(),
    )
    db.add(new_request)
    db.commit()
    db.refresh(new_request)
    return new_request
