"use client";

// Intervention Requests' main screen: a table of requests with add/
// change/delete, following the same dialog/table pattern as
// products-management.tsx. request_number ("Aanvraagnummer") is the
// first column, generated by the backend — it's shown but never part of
// the create/edit form. status_id is picked from the statuses fetched by
// the Intervention Statuses screen (see intervention-status-management.tsx),
// and team_id ("Ploeg") from MasterData's teams, fetched via module-3's
// own "/teams" endpoint (see listInterventionRequestsTeams in api.ts).

import { Fragment, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, FileText, Layers, Pencil, Trash2 } from "lucide-react";
import { useLocale, useTranslations } from "next-intl";
import { toast } from "sonner";
import { useRouter } from "@/i18n/navigation";
import {
  ApiError,
  createInterventionRequest,
  deleteInterventionRequest,
  updateInterventionRequest,
} from "@/lib/api";
import { API_BASE_URL } from "@/lib/config";
import type {
  InterventionRequest,
  InterventionRequestInput,
  InterventionRequestsTeam,
  InterventionStatus,
  TeamKarMemberOption,
} from "@/lib/types";
import { isStatusColorKey, STATUS_COLOR_INFO } from "@/lib/status-colors";
import { cn, formatPhoneNumber } from "@/lib/utils";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { TeamCombobox } from "./team-combobox";

interface InterventionRequestsManagementProps {
  initialRequests: InterventionRequest[];
  statuses: InterventionStatus[];
  teams: InterventionRequestsTeam[];
  teamKarMembers: TeamKarMemberOption[];
}

/** Plain string slicing instead of toLocaleString(): that depends on the
 * runtime's default locale/timezone, which differs between the server
 * (during SSR) and the browser (during hydration) — causing a hydration
 * mismatch. Slicing the already-ISO string is deterministic everywhere
 * (see tag-linedata.tsx's identical helper).
 */
function formatDateTime(isoDateTime: string | null): string {
  return isoDateTime ? isoDateTime.slice(0, 16).replace("T", " ") : "";
}

/** "YYYY-MM-DDTHH:mm", the value shape <input type="datetime-local">
 * expects — just the first 16 characters of an ISO string.
 */
function toDateTimeLocalValue(isoDateTime: string | null): string {
  return isoDateTime ? isoDateTime.slice(0, 16) : "";
}

/** The status a brand-new request should default to, so staff don't have
 * to remember to set it themselves every time — matched by name against
 * the live statuses list (ids are generated, so can't be hardcoded).
 * Falls back to unselected if no status is literally named "Nieuw".
 */
function defaultStatusId(statuses: InterventionStatus[]): number {
  return statuses.find((status) => status.name === "Nieuw")?.id ?? 0;
}

/** "dd-mm-yyyy", for a group's date subtitle — takes the date-only
 * "YYYY-MM-DD" slice already used as this table's grouping key, distinct
 * from formatDateTime's HH:mm-inclusive table-cell format.
 */
function formatDateOnly(dateOnly: string): string {
  const [year, month, day] = dateOnly.split("-");
  return `${day}-${month}-${year}`;
}

/** Translation keys for interventionRequests.requests.weekdays, indexed
 * exactly like Date#getUTCDay() (0 = Sunday .. 6 = Saturday).
 */
const WEEKDAY_KEYS = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const;

/** Which weekday a "YYYY-MM-DD" date key falls on — parsed as UTC
 * midnight (not the runtime's local timezone) so it's the same on the
 * server and in the browser, same deterministic-parsing reasoning as
 * formatDateTime/formatDateOnly avoiding toLocaleString elsewhere in this
 * file.
 */
function weekdayKeyFor(dateOnly: string): (typeof WEEKDAY_KEYS)[number] {
  return WEEKDAY_KEYS[new Date(`${dateOnly}T00:00:00Z`).getUTCDay()];
}

const ALL_VALUE = "all";
/** Groups requests with no preferred_delivery_at set — sorts first,
 * ahead of every real "YYYY-MM-DD" date key (see groupedBlocks below).
 */
const NO_PREFERENCE_KEY = "__no_preference__";

function textMatches(fieldValue: string | number | null, filterValue: string): boolean {
  if (!filterValue) return true;
  return String(fieldValue ?? "")
    .toLowerCase()
    .includes(filterValue.toLowerCase());
}

/** Every column a user can click to sort by — see getSortValue for how
 * each one is turned into a comparable value (looked-up display names for
 * the status/team/team-cart columns, the raw field otherwise).
 */
type SortableColumn =
  | "request_number"
  | "status"
  | "submitted_at"
  | "team"
  | "cart_number"
  | "question"
  | "employee_name"
  | "employee_phone"
  | "preferred_delivery_at"
  | "delivery_location"
  | "zone"
  | "team_cart";

type SortDirection = "asc" | "desc";

/** One date-grouped cluster of requests, built when "Groepeer op Voorkeur
 * Levering" is on (see groupedBlocks) — every visible request belongs to
 * exactly one group, unlike tag-linedata.tsx's mixed line/group blocks.
 */
interface RequestGroup {
  key: string;
  dateLabel: string;
  requests: InterventionRequest[];
}

interface SortableHeaderProps {
  label: string;
  column: SortableColumn;
  activeColumn: SortableColumn | null;
  direction: SortDirection;
  onSort: (column: SortableColumn) => void;
  /** True while grouping is active — sorting and grouping are two
   *  different orderings of the same rows, so sorting is inert (but still
   *  visible, dimmed) until grouping is turned back off.
   */
  disabled?: boolean;
  className?: string;
}

/** A column header that's both the mandatory bold+underlined label AND
 * the click target to sort by that column — an arrow shows the current
 * sort direction on the active column, and a faint neutral icon on every
 * other column hints that it's clickable too (see tag-linedata.tsx's
 * identical component).
 */
function SortableHeader({ label, column, activeColumn, direction, onSort, disabled, className }: SortableHeaderProps) {
  const isActive = activeColumn === column && !disabled;
  return (
    <TableHead className={cn("select-none font-bold underline", disabled ? "cursor-default" : "cursor-pointer", className)}>
      <button
        type="button"
        onClick={() => onSort(column)}
        disabled={disabled}
        className="inline-flex w-full items-center gap-1 text-left disabled:cursor-default"
      >
        {label}
        {isActive ? (
          direction === "asc" ? (
            <ArrowUp className="size-3.5" />
          ) : (
            <ArrowDown className="size-3.5" />
          )
        ) : (
          <ArrowUpDown className={cn("size-3.5 text-muted-foreground/50", disabled && "opacity-40")} />
        )}
      </button>
    </TableHead>
  );
}

const EMPTY_FORM: InterventionRequestInput = {
  team_id: null,
  team_name: null,
  cart_number: "",
  question: "",
  employee_name: "",
  employee_phone: "",
  preferred_delivery_at: "",
  delivery_location: "",
  zone: "",
  status_id: 0,
  handled_by: "",
  team_cart_user_id: null,
};

function toFormValues(request: InterventionRequest): InterventionRequestInput {
  return {
    team_id: request.team_id,
    team_name: request.team_name,
    cart_number: request.cart_number ?? "",
    question: request.question,
    employee_name: request.employee_name ?? "",
    employee_phone: request.employee_phone ?? "",
    preferred_delivery_at: toDateTimeLocalValue(request.preferred_delivery_at),
    delivery_location: request.delivery_location ?? "",
    zone: request.zone ?? "",
    status_id: request.status_id,
    handled_by: request.handled_by ?? "",
    team_cart_user_id: request.team_cart_user_id,
  };
}

// Requests can also arrive from the public, no-login form (see
// (public)/intervention-request) — from any customer's phone, not
// necessarily this admin's own actions — so an already-open list has no
// other way to learn about them. Polling is the simplest fix given there's
// no push/websocket channel here; 15s keeps new requests showing up
// promptly without hammering the backend.
const REQUESTS_POLL_INTERVAL_MS = 15_000;

export function InterventionRequestsManagement({
  initialRequests,
  statuses,
  teams,
  teamKarMembers,
}: InterventionRequestsManagementProps) {
  const t = useTranslations("interventionRequests.requests");
  const router = useRouter();
  const locale = useLocale();

  const [requests, setRequests] = useState(initialRequests);
  // router.refresh() re-runs the server component and hands this
  // component a fresh `initialRequests` prop each poll — but useState only
  // reads its initial value once, so this tracks the last prop we synced
  // from and, when it changes, updates `requests` during render itself
  // (React's documented way to adjust state from a changed prop, cheaper
  // than doing the same setState from inside an effect).
  const [syncedRequests, setSyncedRequests] = useState(initialRequests);
  if (initialRequests !== syncedRequests) {
    setSyncedRequests(initialRequests);
    setRequests(initialRequests);
  }

  useEffect(() => {
    const intervalId = setInterval(() => router.refresh(), REQUESTS_POLL_INTERVAL_MS);
    return () => clearInterval(intervalId);
  }, [router]);
  // Starts filtered to open-status requests, per the "Open Interventies"
  // default — see isStatusOpen/visibleRequests below.
  const [showOnlyOpen, setShowOnlyOpen] = useState(true);
  // On by default, so requests are grouped by delivery date right away.
  // Grouping and column sorting are mutually exclusive (see SortableHeader's
  // "disabled" prop below) — grouping takes over the row order while on.
  const [groupByDelivery, setGroupByDelivery] = useState(true);

  // One filter per column, mirroring tag-linedata.tsx's per-column filter
  // row — status uses a <Select> (small, fixed-ish list) like that
  // screen's own "status" filter; every other column is free-text,
  // matched against the column's *displayed* value (see textMatches below).
  const [requestNumberFilter, setRequestNumberFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState(ALL_VALUE);
  const [submittedAtFilter, setSubmittedAtFilter] = useState("");
  const [teamFilter, setTeamFilter] = useState("");
  const [cartNumberFilter, setCartNumberFilter] = useState("");
  const [questionFilter, setQuestionFilter] = useState("");
  const [employeeNameFilter, setEmployeeNameFilter] = useState("");
  const [employeePhoneFilter, setEmployeePhoneFilter] = useState("");
  const [preferredDeliveryAtFilter, setPreferredDeliveryAtFilter] = useState("");
  const [deliveryLocationFilter, setDeliveryLocationFilter] = useState("");
  const [zoneFilter, setZoneFilter] = useState("");
  const [teamCartFilter, setTeamCartFilter] = useState("");

  const [sortColumn, setSortColumn] = useState<SortableColumn | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>("asc");

  function handleSort(column: SortableColumn) {
    if (sortColumn === column) {
      setSortDirection((current) => (current === "asc" ? "desc" : "asc"));
    } else {
      setSortColumn(column);
      setSortDirection("asc");
    }
  }

  function statusNameFor(statusId: number) {
    return statuses.find((status) => status.id === statusId)?.name ?? "";
  }

  function teamNameFor(teamId: number) {
    return teams.find((team) => team.id === teamId)?.name ?? "";
  }

  /** A request's "Ploeg" as shown in the table/filters/sort — the looked-up
   *  MasterData team name, or the free-text team_name typed on the public
   *  form when the request has no team_id (see TeamCombobox). */
  function teamDisplayFor(request: InterventionRequest) {
    return request.team_id != null ? teamNameFor(request.team_id) : (request.team_name ?? "");
  }

  function teamKarNameFor(userId: number | null) {
    return teamKarMembers.find((member) => member.id === userId)?.display_name ?? "";
  }

  /** The status colour key assigned to a request's status, if any — used
   *  to colour that request's whole row (see the tr[data-status-color]
   *  rule in globals.css). */
  function statusColorFor(statusId: number): string | undefined {
    return statuses.find((status) => status.id === statusId)?.color;
  }

  /** Whether a request's status is currently marked "Open" — used by the
   *  "Toon Alle/Open Interventies" toggle below. Defaults to true (shown)
   *  if the status can't be found, the same "fail open" fallback as the
   *  other lookups here. */
  function isStatusOpen(statusId: number): boolean {
    return statuses.find((status) => status.id === statusId)?.is_open ?? true;
  }

  const visibleRequests = showOnlyOpen ? requests.filter((request) => isStatusOpen(request.status_id)) : requests;

  /** The value a column sorts and filters by — the looked-up *display*
   *  value for the status/team/team-cart columns (so sorting "Status"
   *  sorts alphabetically by status name, not by its internal id), the
   *  raw field otherwise. Dates are kept as their ISO strings, which sort
   *  correctly as plain strings.
   */
  function getColumnValue(request: InterventionRequest, column: SortableColumn): string | null {
    switch (column) {
      case "request_number":
        return request.request_number;
      case "status":
        return statusNameFor(request.status_id);
      case "submitted_at":
        return request.submitted_at;
      case "team":
        return teamDisplayFor(request);
      case "cart_number":
        return request.cart_number;
      case "question":
        return request.question;
      case "employee_name":
        return request.employee_name;
      case "employee_phone":
        return request.employee_phone;
      case "preferred_delivery_at":
        return request.preferred_delivery_at;
      case "delivery_location":
        return request.delivery_location;
      case "zone":
        return request.zone;
      case "team_cart":
        return teamKarNameFor(request.team_cart_user_id);
    }
  }

  const filteredRequests = useMemo(() => {
    return visibleRequests.filter((request) => {
      if (!textMatches(getColumnValue(request, "request_number"), requestNumberFilter)) return false;
      if (statusFilter !== ALL_VALUE && String(request.status_id) !== statusFilter) return false;
      if (!textMatches(formatDateTime(request.submitted_at), submittedAtFilter)) return false;
      if (!textMatches(getColumnValue(request, "team"), teamFilter)) return false;
      if (!textMatches(request.cart_number, cartNumberFilter)) return false;
      if (!textMatches(request.question, questionFilter)) return false;
      if (!textMatches(request.employee_name, employeeNameFilter)) return false;
      if (!textMatches(request.employee_phone, employeePhoneFilter)) return false;
      if (!textMatches(formatDateTime(request.preferred_delivery_at), preferredDeliveryAtFilter)) return false;
      if (!textMatches(request.delivery_location, deliveryLocationFilter)) return false;
      if (!textMatches(request.zone, zoneFilter)) return false;
      if (!textMatches(getColumnValue(request, "team_cart"), teamCartFilter)) return false;
      return true;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    visibleRequests,
    requestNumberFilter,
    statusFilter,
    submittedAtFilter,
    teamFilter,
    cartNumberFilter,
    questionFilter,
    employeeNameFilter,
    employeePhoneFilter,
    preferredDeliveryAtFilter,
    deliveryLocationFilter,
    zoneFilter,
    teamCartFilter,
  ]);

  const sortedRequests = useMemo(() => {
    if (!sortColumn) return filteredRequests;

    const factor = sortDirection === "asc" ? 1 : -1;
    return [...filteredRequests].sort((a, b) => {
      const aValue = getColumnValue(a, sortColumn);
      const bValue = getColumnValue(b, sortColumn);
      // Missing values always sort last, regardless of direction — a
      // blank cell isn't meaningfully "smaller" or "larger" than a real one.
      if (aValue == null && bValue == null) return 0;
      if (aValue == null) return 1;
      if (bValue == null) return -1;
      return String(aValue).localeCompare(String(bValue)) * factor;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filteredRequests, sortColumn, sortDirection]);

  // Built from filteredRequests (not sortedRequests): grouping is its own
  // ordering of the currently-filtered rows, applied instead of — not on
  // top of — column sorting (see SortableHeader's `disabled` prop below).
  // Every visible request belongs to exactly one group: a real delivery
  // date, or the "Geen voorkeur" group for requests with none set — that
  // group is always shown first, ahead of every dated group.
  const groupedRequests = useMemo<RequestGroup[]>(() => {
    const groupsByKey = new Map<string, InterventionRequest[]>();

    for (const request of filteredRequests) {
      const key = request.preferred_delivery_at ? request.preferred_delivery_at.slice(0, 10) : NO_PREFERENCE_KEY;
      const group = groupsByKey.get(key);
      if (group) {
        group.push(request);
      } else {
        groupsByKey.set(key, [request]);
      }
    }

    const sortedKeys = [...groupsByKey.keys()].sort((a, b) => {
      if (a === NO_PREFERENCE_KEY) return -1;
      if (b === NO_PREFERENCE_KEY) return 1;
      return a.localeCompare(b);
    });

    return sortedKeys.map((key) => {
      const requestsInGroup = groupsByKey.get(key)!;
      // Rows within a dated group are ordered ascending by the full
      // timestamp, not just the date — the no-preference group has no
      // time to sort by, so it keeps its filtered order.
      const orderedRequests =
        key === NO_PREFERENCE_KEY
          ? requestsInGroup
          : [...requestsInGroup].sort((a, b) =>
              (a.preferred_delivery_at ?? "").localeCompare(b.preferred_delivery_at ?? ""),
            );
      return {
        key,
        dateLabel:
          key === NO_PREFERENCE_KEY
            ? t("noPreferenceGroupLabel")
            : `${t(`weekdays.${weekdayKeyFor(key)}`)} ${formatDateOnly(key)}`,
        requests: orderedRequests,
      };
    });
  }, [filteredRequests, t]);

  function upsert(updated: InterventionRequest) {
    setRequests((current) => {
      const exists = current.some((request) => request.id === updated.id);
      return exists
        ? current.map((request) => (request.id === updated.id ? updated : request))
        : [updated, ...current];
    });
    router.refresh();
  }

  function renderRequestRow(request: InterventionRequest) {
    const statusColor = statusColorFor(request.status_id);
    return (
      <TableRow
        key={request.id}
        className={cn("group", statusColor && isStatusColorKey(statusColor) && STATUS_COLOR_INFO[statusColor].textClassName)}
        data-status-color={statusColor}
      >
        <TableCell className="font-medium whitespace-nowrap">{request.request_number}</TableCell>
        <TableCell>{statusNameFor(request.status_id)}</TableCell>
        <TableCell className="whitespace-nowrap text-muted-foreground">{formatDateTime(request.submitted_at)}</TableCell>
        <TableCell>{teamDisplayFor(request)}</TableCell>
        <TableCell className="text-muted-foreground">{request.cart_number}</TableCell>
        <TableCell className="max-w-[280px] truncate text-muted-foreground" title={request.question}>
          {request.question}
        </TableCell>
        <TableCell className="text-muted-foreground">{request.employee_name}</TableCell>
        <TableCell className="text-muted-foreground">{request.employee_phone}</TableCell>
        <TableCell className="whitespace-nowrap text-muted-foreground">
          {formatDateTime(request.preferred_delivery_at)}
        </TableCell>
        <TableCell className="text-muted-foreground">{request.delivery_location}</TableCell>
        <TableCell className="text-muted-foreground">{request.zone}</TableCell>
        <TableCell className="text-muted-foreground">{teamKarNameFor(request.team_cart_user_id)}</TableCell>
        <TableCell className="sticky right-0 z-10 bg-background group-hover:bg-muted/50">
          <div className="flex justify-end gap-1">
            <a
              href={`${API_BASE_URL}/api/modules/module-3/intervention-requests/${request.id}/pdf?locale=${locale}`}
              aria-label={t("downloadDeliveryNote")}
              title={t("downloadDeliveryNote")}
              className="inline-flex size-9 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
            >
              <FileText className="size-4" />
            </a>
            <RequestFormDialog
              request={request}
              trigger={
                <Button variant="ghost" size="icon" aria-label={t("change")} title={t("change")}>
                  <Pencil className="size-4" />
                </Button>
              }
              onSaved={upsert}
              statuses={statuses}
              teams={teams}
              teamKarMembers={teamKarMembers}
            />
            <DeleteRequestAlertDialog
              request={request}
              onDeleted={(requestId) => {
                setRequests((current) => current.filter((item) => item.id !== requestId));
                router.refresh();
              }}
            />
          </div>
        </TableCell>
      </TableRow>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight underline">{t("title")}</h1>
          <p className="text-muted-foreground">{t("description")}</p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant={groupByDelivery ? "default" : "outline"}
            onClick={() => setGroupByDelivery((current) => !current)}
          >
            <Layers className="size-4" />
            {t("groupByDeliveryButton")}
          </Button>
          <Button variant="outline" onClick={() => setShowOnlyOpen((current) => !current)}>
            {showOnlyOpen ? t("showAllInterventions") : t("showOpenInterventions")}
          </Button>
          <div className="flex flex-col items-end gap-1">
            <RequestFormDialog
              trigger={<Button>{t("newRequest")}</Button>}
              onSaved={upsert}
              statuses={statuses}
              teams={teams}
              teamKarMembers={teamKarMembers}
            />
            {/* Test-only link to the public, no-login intervention-request
                form (see frontend/src/app/[locale]/(public)/intervention-request)
                — the QR code that will eventually link here doesn't exist
                yet, so this is a quick way to open and pre-fill it by hand.
                Uses the first known team so clicking it also proves the
                Ploeg/Karnr/Afleverplaats/Zone pre-fill actually works. */}
            <a
              href={`/${locale}/intervention-request?${new URLSearchParams({
                ...(teams[0] ? { team_id: String(teams[0].id) } : {}),
                cart_number: "TEST-01",
                delivery_location: "Testlocatie",
                zone: "Testzone",
              }).toString()}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-muted-foreground underline hover:text-foreground"
            >
              {t("publicFormTestLink")}
            </a>
          </div>
        </div>
      </div>

      {/* <Table> itself wraps the <table> in its own scrolling div
          (data-slot="table-container", already overflow-x-auto) — bound
          THAT element's height and give it overflow-y too, via the
          [&>div] arbitrary-variant selector, rather than adding another
          wrapping div of our own (see tag-linedata.tsx's identical
          reasoning). Both header rows are sticky so they (and the
          filters) stay visible while scrolling through the results. */}
      <div className="rounded-md border [&>div]:max-h-[65vh] [&>div]:overflow-y-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <SortableHeader
                label={t("columnRequestNumber")}
                column="request_number"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnStatus")}
                column="status"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnSubmittedAt")}
                column="submitted_at"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnAssociationName")}
                column="team"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnCartNumber")}
                column="cart_number"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnQuestion")}
                column="question"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnEmployeeName")}
                column="employee_name"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnEmployeePhone")}
                column="employee_phone"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnPreferredDeliveryAt")}
                column="preferred_delivery_at"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnDeliveryLocation")}
                column="delivery_location"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnZone")}
                column="zone"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              <SortableHeader
                label={t("columnTeamCart")}
                column="team_cart"
                activeColumn={sortColumn}
                direction={sortDirection}
                onSort={handleSort}
                disabled={groupByDelivery}
                className="sticky top-0 z-20 bg-background"
              />
              {/* "Uitvoerder" (handled_by) is intentionally not shown as a
                  column here — the field still exists in the create/change
                  dialog and the API, it's just hidden from this table. */}
              {/* Actions stays pinned to the top+right corner while the
                  rest of the table scrolls both ways (see
                  tag-linedata.tsx's identical Actions treatment). */}
              <TableHead className="sticky top-0 right-0 z-30 bg-background text-right font-bold underline">
                {t("tableActions")}
              </TableHead>
            </TableRow>
            {/* The filter row: each control sits directly under the column it filters. */}
            <TableRow>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterRequestNumber")}
                  placeholder={t("filterRequestNumber")}
                  className="h-8 w-full min-w-28 font-normal"
                  value={requestNumberFilter}
                  onChange={(event) => setRequestNumberFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Select value={statusFilter} onValueChange={(value) => setStatusFilter(value ?? ALL_VALUE)}>
                  <SelectTrigger aria-label={t("filterStatus")} className="h-8 w-full font-normal">
                    <SelectValue>
                      {(value: string | null) =>
                        value && value !== ALL_VALUE
                          ? (statuses.find((status) => String(status.id) === value)?.name ?? "")
                          : t("allStatuses")
                      }
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={ALL_VALUE}>{t("allStatuses")}</SelectItem>
                    {statuses.map((status) => (
                      <SelectItem key={status.id} value={String(status.id)}>
                        {status.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterSubmittedAt")}
                  placeholder={t("filterSubmittedAt")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={submittedAtFilter}
                  onChange={(event) => setSubmittedAtFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterTeam")}
                  placeholder={t("filterTeam")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={teamFilter}
                  onChange={(event) => setTeamFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterCartNumber")}
                  placeholder={t("filterCartNumber")}
                  className="h-8 w-full min-w-24 font-normal"
                  value={cartNumberFilter}
                  onChange={(event) => setCartNumberFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterQuestion")}
                  placeholder={t("filterQuestion")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={questionFilter}
                  onChange={(event) => setQuestionFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterEmployeeName")}
                  placeholder={t("filterEmployeeName")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={employeeNameFilter}
                  onChange={(event) => setEmployeeNameFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterEmployeePhone")}
                  placeholder={t("filterEmployeePhone")}
                  className="h-8 w-full min-w-28 font-normal"
                  value={employeePhoneFilter}
                  onChange={(event) => setEmployeePhoneFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterPreferredDeliveryAt")}
                  placeholder={t("filterPreferredDeliveryAt")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={preferredDeliveryAtFilter}
                  onChange={(event) => setPreferredDeliveryAtFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterDeliveryLocation")}
                  placeholder={t("filterDeliveryLocation")}
                  className="h-8 w-full min-w-32 font-normal"
                  value={deliveryLocationFilter}
                  onChange={(event) => setDeliveryLocationFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterZone")}
                  placeholder={t("filterZone")}
                  className="h-8 w-full min-w-24 font-normal"
                  value={zoneFilter}
                  onChange={(event) => setZoneFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 z-20 bg-background">
                <Input
                  aria-label={t("filterTeamCart")}
                  placeholder={t("filterTeamCart")}
                  className="h-8 w-full min-w-28 font-normal"
                  value={teamCartFilter}
                  onChange={(event) => setTeamCartFilter(event.target.value)}
                />
              </TableHead>
              <TableHead className="sticky top-10 right-0 z-30 bg-background" />
            </TableRow>
          </TableHeader>
          <TableBody>
            {groupByDelivery
              ? groupedRequests.map((group) => (
                  <Fragment key={group.key}>
                    <TableRow className="bg-muted/50 hover:bg-muted/50">
                      <TableCell colSpan={13} className="font-semibold">
                        {group.dateLabel}
                      </TableCell>
                    </TableRow>
                    {group.requests.map((request) => renderRequestRow(request))}
                  </Fragment>
                ))
              : sortedRequests.map((request) => renderRequestRow(request))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

interface RequestFormDialogProps {
  request?: InterventionRequest;
  trigger: React.ReactElement;
  onSaved: (request: InterventionRequest) => void;
  statuses: InterventionStatus[];
  teams: InterventionRequestsTeam[];
  teamKarMembers: TeamKarMemberOption[];
}

function RequestFormDialog({ request, trigger, onSaved, statuses, teams, teamKarMembers }: RequestFormDialogProps) {
  const t = useTranslations("interventionRequests.requests");
  const isEditing = request !== undefined;
  const [isOpen, setIsOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [form, setForm] = useState<InterventionRequestInput>(
    request ? toFormValues(request) : { ...EMPTY_FORM, status_id: defaultStatusId(statuses) },
  );

  function handleOpenChange(open: boolean) {
    setIsOpen(open);
    if (open) {
      // Start from the request's latest known values each time the dialog
      // is opened, in case they changed since last time; a new request
      // defaults to the "Nieuw" status instead of starting unselected.
      setForm(request ? toFormValues(request) : { ...EMPTY_FORM, status_id: defaultStatusId(statuses) });
    }
  }

  function updateField<K extends keyof InterventionRequestInput>(field: K, value: InterventionRequestInput[K]) {
    setForm((current) => ({ ...current, [field]: value }));
  }

  async function handleSubmit() {
    setIsSubmitting(true);
    try {
      const payload: InterventionRequestInput = {
        ...form,
        preferred_delivery_at: form.preferred_delivery_at || null,
      };
      const savedRequest = isEditing
        ? await updateInterventionRequest(request.id, payload)
        : await createInterventionRequest(payload);
      toast.success(isEditing ? t("requestUpdated") : t("requestCreated"));
      onSaved(savedRequest);
      setIsOpen(false);
    } catch (error) {
      const message = error instanceof ApiError ? error.message : isEditing ? t("updateFailed") : t("createFailed");
      toast.error(message);
    } finally {
      setIsSubmitting(false);
    }
  }

  const canSubmit = Boolean((form.team_id || form.team_name?.trim()) && form.question.trim() && form.status_id);

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger render={trigger} />
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>{isEditing ? t("changeTitle") : t("createTitle")}</DialogTitle>
          <DialogDescription>{isEditing ? t("changeDescription") : t("createDescription")}</DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-2 gap-4">
          <div className="col-span-2">
            <TeamCombobox
              id="request-team"
              label={t("associationNameLabel")}
              teams={teams}
              teamId={form.team_id}
              teamName={form.team_name ?? null}
              otherOptionLabel={t("otherTeamOption")}
              otherPlaceholder={t("teamNamePlaceholder")}
              onChange={(next) => setForm((current) => ({ ...current, ...next }))}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="request-cart-number">{t("cartNumberLabel")}</Label>
            <Input
              id="request-cart-number"
              value={form.cart_number ?? ""}
              onChange={(event) => updateField("cart_number", event.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="request-status">{t("statusLabel")}</Label>
            <Select
              value={form.status_id ? String(form.status_id) : ""}
              onValueChange={(value) => updateField("status_id", Number(value))}
            >
              <SelectTrigger id="request-status">
                <SelectValue>
                  {(value: string | null) => statuses.find((status) => String(status.id) === value)?.name ?? ""}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                {statuses.map((status) => (
                  <SelectItem key={status.id} value={String(status.id)}>
                    {status.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="col-span-2 flex flex-col gap-2">
            <Label htmlFor="request-question">{t("questionLabel")}</Label>
            <Textarea
              id="request-question"
              value={form.question}
              onChange={(event) => updateField("question", event.target.value)}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="request-employee-name">{t("employeeNameLabel")}</Label>
            <Input
              id="request-employee-name"
              value={form.employee_name ?? ""}
              onChange={(event) => updateField("employee_name", event.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="request-employee-phone">{t("employeePhoneLabel")}</Label>
            <Input
              id="request-employee-phone"
              type="tel"
              value={form.employee_phone ?? ""}
              onChange={(event) => updateField("employee_phone", formatPhoneNumber(event.target.value))}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="request-preferred-delivery">{t("preferredDeliveryAtLabel")}</Label>
            <Input
              id="request-preferred-delivery"
              type="datetime-local"
              value={form.preferred_delivery_at ?? ""}
              onChange={(event) => updateField("preferred_delivery_at", event.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="request-delivery-location">{t("deliveryLocationLabel")}</Label>
            <Input
              id="request-delivery-location"
              value={form.delivery_location ?? ""}
              onChange={(event) => updateField("delivery_location", event.target.value)}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="request-zone">{t("zoneLabel")}</Label>
            <Input
              id="request-zone"
              value={form.zone ?? ""}
              onChange={(event) => updateField("zone", event.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="request-handled-by">{t("handledByLabel")}</Label>
            <Input
              id="request-handled-by"
              value={form.handled_by ?? ""}
              onChange={(event) => updateField("handled_by", event.target.value)}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="request-team-cart">{t("teamCartLabel")}</Label>
            <Select
              value={form.team_cart_user_id ? String(form.team_cart_user_id) : "__none__"}
              onValueChange={(value) => updateField("team_cart_user_id", value === "__none__" ? null : Number(value))}
            >
              <SelectTrigger id="request-team-cart">
                <SelectValue>
                  {(value: string | null) =>
                    value && value !== "__none__"
                      ? (teamKarMembers.find((member) => String(member.id) === value)?.display_name ?? "")
                      : t("noneOption")
                  }
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__none__">{t("noneOption")}</SelectItem>
                {teamKarMembers.map((member) => (
                  <SelectItem key={member.id} value={String(member.id)}>
                    {member.display_name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <DialogFooter>
          <Button onClick={handleSubmit} disabled={isSubmitting || !canSubmit}>
            {isEditing ? t("change") : t("newRequest")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

interface DeleteRequestAlertDialogProps {
  request: InterventionRequest;
  onDeleted: (requestId: number) => void;
}

function DeleteRequestAlertDialog({ request, onDeleted }: DeleteRequestAlertDialogProps) {
  const t = useTranslations("interventionRequests.requests");
  const tCommon = useTranslations("common");
  const [isOpen, setIsOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  async function handleConfirmDelete() {
    setIsDeleting(true);
    try {
      await deleteInterventionRequest(request.id);
      toast.success(t("requestDeleted"));
      onDeleted(request.id);
      setIsOpen(false);
    } catch (error) {
      const message = error instanceof ApiError ? error.message : t("deleteFailed");
      toast.error(message);
    } finally {
      setIsDeleting(false);
    }
  }

  return (
    <AlertDialog open={isOpen} onOpenChange={setIsOpen}>
      <AlertDialogTrigger
        render={
          <Button variant="ghost" size="icon" aria-label={t("delete")} title={t("delete")}>
            <Trash2 className="size-4 text-destructive" />
          </Button>
        }
      />
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{t("deleteConfirmTitle")}</AlertDialogTitle>
          <AlertDialogDescription>
            {t("deleteConfirmDescription", { requestNumber: request.request_number })}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>{tCommon("cancel")}</AlertDialogCancel>
          <AlertDialogAction variant="destructive" disabled={isDeleting} onClick={handleConfirmDelete}>
            {t("delete")}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
