"""add intervention requests and statuses tables

Revision ID: 07dca593742e
Revises: 733ddf4ec3d0
Create Date: 2026-09-06 21:29:06.853330

Creates the two tables behind module-3's new "Intervention Requests" and
"Intervention Statuses" screens, and seeds the 5 status values already in
use on the reference spreadsheet so the status dropdown isn't empty.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dca593742e'
down_revision: Union[str, Sequence[str], None] = '733ddf4ec3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InterventionRequests_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InterventionRequests_status_name'), 'InterventionRequests_status', ['name'], unique=True)
    op.create_table('InterventionRequests_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('association_name', sa.String(length=255), nullable=False),
    sa.Column('cart_number', sa.String(length=50), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('employee_phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('handled_by', sa.String(length=255), nullable=True),
    sa.Column('team_cart', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['InterventionRequests_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InterventionRequests_request_request_number'), 'InterventionRequests_request', ['request_number'], unique=True)
    # ### end Alembic commands ###

    # Seed the 5 statuses already in use on the current reference
    # spreadsheet, so the Intervention Requests form's status dropdown
    # isn't empty the first time anyone opens it.
    op.execute(
        """
        INSERT INTO "InterventionRequests_status" (name) VALUES
            ('Open'),
            ('Geleverd'),
            ('Gecanceled'),
            ('Geweigerd door Altsien'),
            ('Niet voor Team Kar')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_InterventionRequests_request_request_number'), table_name='InterventionRequests_request')
    op.drop_table('InterventionRequests_request')
    op.drop_index(op.f('ix_InterventionRequests_status_name'), table_name='InterventionRequests_status')
    op.drop_table('InterventionRequests_status')
    # ### end Alembic commands ###
