"""add team and team join tables

Revision ID: 0a5007b9640a
Revises: 165f1df81f16
Create Date: 2026-09-06 19:25:50.784507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5007b9640a'
down_revision: Union[str, Sequence[str], None] = '165f1df81f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterData_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_method_id'], ['MasterData_delivery_method.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['MasterData_team_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_team_name'), 'MasterData_team', ['name'], unique=True)
    op.create_table('MasterData_team_kernlid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('altsien_kernlid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['altsien_kernlid_id'], ['MasterData_altsien_kernlid.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['MasterData_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'altsien_kernlid_id', name='uq_masterdata_team_kernlid')
    )
    op.create_table('MasterData_team_team_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['MasterData_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_task_id'], ['MasterData_team_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'team_task_id', name='uq_masterdata_team_team_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MasterData_team_team_task')
    op.drop_table('MasterData_team_kernlid')
    op.drop_index(op.f('ix_MasterData_team_name'), table_name='MasterData_team')
    op.drop_table('MasterData_team')
    # ### end Alembic commands ###
