"""add landing_md_season table

Revision ID: 0a90973229bd
Revises: 51a15c8d59d2
Create Date: 2026-08-29 21:37:04.323035

Auto-generated by Alembic from the new Season model (see
app/db/models/season.py) — the first "master data" table, managed from
the landing page's admin sidebar. Named "landing_md_season" exactly as
requested (all lowercase), separately from the "Landing_"-prefixed
tables from the earlier rename.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a90973229bd'
down_revision: Union[str, Sequence[str], None] = '51a15c8d59d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_md_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_md_season_name'), 'landing_md_season', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_md_season_name'), table_name='landing_md_season')
    op.drop_table('landing_md_season')
    # ### end Alembic commands ###
