"""add kartracker distributiepunt zone afleverlocatie tables

Revision ID: 10f588a47567
Revises: c1761ac3bf9a
Create Date: 2026-09-14 20:54:02.589441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f588a47567'
down_revision: Union[str, Sequence[str], None] = 'c1761ac3bf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KarTracker_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_zones_name'), 'KarTracker_zones', ['name'], unique=True)
    op.create_table('KarTracker_distributiepunten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('terrein_positie', sa.String(length=255), nullable=True),
    sa.Column('altsien_kernlid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['altsien_kernlid_id'], ['MasterData_altsien_kernlid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_distributiepunten_name'), 'KarTracker_distributiepunten', ['name'], unique=True)
    op.create_table('KarTracker_afleverlocaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('distributiepunt_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('terrein_positie', sa.String(length=255), nullable=True),
    sa.Column('altsien_kernlid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['altsien_kernlid_id'], ['MasterData_altsien_kernlid.id'], ),
    sa.ForeignKeyConstraint(['distributiepunt_id'], ['KarTracker_distributiepunten.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['KarTracker_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_afleverlocaties_name'), 'KarTracker_afleverlocaties', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_KarTracker_afleverlocaties_name'), table_name='KarTracker_afleverlocaties')
    op.drop_table('KarTracker_afleverlocaties')
    op.drop_index(op.f('ix_KarTracker_distributiepunten_name'), table_name='KarTracker_distributiepunten')
    op.drop_table('KarTracker_distributiepunten')
    op.drop_index(op.f('ix_KarTracker_zones_name'), table_name='KarTracker_zones')
    op.drop_table('KarTracker_zones')
    # ### end Alembic commands ###
