"""add team location, delivery method, and team task tables

Revision ID: 125321cd1792
Revises: 3b490fb1dc14
Create Date: 2026-09-05 19:02:20.464790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125321cd1792'
down_revision: Union[str, Sequence[str], None] = '3b490fb1dc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterData_delivery_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_method', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_delivery_method_delivery_method'), 'MasterData_delivery_method', ['delivery_method'], unique=True)
    op.create_table('MasterData_team_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_team_location_location'), 'MasterData_team_location', ['location'], unique=True)
    op.create_table('MasterData_team_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_tasks', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_team_task_team_tasks'), 'MasterData_team_task', ['team_tasks'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MasterData_team_task_team_tasks'), table_name='MasterData_team_task')
    op.drop_table('MasterData_team_task')
    op.drop_index(op.f('ix_MasterData_team_location_location'), table_name='MasterData_team_location')
    op.drop_table('MasterData_team_location')
    op.drop_index(op.f('ix_MasterData_delivery_method_delivery_method'), table_name='MasterData_delivery_method')
    op.drop_table('MasterData_delivery_method')
    # ### end Alembic commands ###
