"""add tagscan device intake

Revision ID: 21278abc915c
Revises: 47a5bbcbeec2
Create Date: 2026-09-12 21:10:14.451013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21278abc915c'
down_revision: Union[str, Sequence[str], None] = '47a5bbcbeec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receive_folder_path', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Tagscan_scanners', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.add_column('Tagscan_scanners', sa.Column('api_key_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Tagscan_scanners', sa.Column('api_key_last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tagscan_scanners', 'api_key_last_used_at')
    op.drop_column('Tagscan_scanners', 'api_key_generated_at')
    op.drop_column('Tagscan_scanners', 'api_key_hash')
    op.drop_table('Tagscan_settings')
    # ### end Alembic commands ###
