"""add kartracker kar actions

Revision ID: 33e7cc110bc7
Revises: e7a4c2b19f53
Create Date: 2026-09-27 09:18:26.293381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e7cc110bc7'
down_revision: Union[str, Sequence[str], None] = 'e7a4c2b19f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KarTracker_kar_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kar_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kar_id'], ['KarTracker_karren.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['KarTracker_kar_statuses.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['MasterData_team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['Landing_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_kar_actions_kar_id'), 'KarTracker_kar_actions', ['kar_id'], unique=False)
    op.create_index(op.f('ix_KarTracker_kar_actions_recorded_at'), 'KarTracker_kar_actions', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_KarTracker_kar_actions_recorded_at'), table_name='KarTracker_kar_actions')
    op.drop_index(op.f('ix_KarTracker_kar_actions_kar_id'), table_name='KarTracker_kar_actions')
    op.drop_table('KarTracker_kar_actions')
    # ### end Alembic commands ###
