"""add tagscan tables

Revision ID: 3508ebb3e74d
Revises: 0a90973229bd
Create Date: 2026-08-30 18:19:21.575033

Auto-generated by Alembic from the four new Tagscan models (see
app/db/models/tagscan_*.py) — Tagscan's own custom-roles-with-per-screen-
permissions system. Also includes one hand-written data change: renaming
Module 1's display name to "Tagscan", now that it has real functionality
instead of being a placeholder (the seed script's seed_modules() only
fills in *missing* modules, so it wouldn't rename an already-existing row).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3508ebb3e74d'
down_revision: Union[str, Sequence[str], None] = '0a90973229bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_roles_name'), 'Tagscan_roles', ['name'], unique=True)
    op.create_table('Tagscan_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_screens_key'), 'Tagscan_screens', ['key'], unique=True)
    op.create_table('Tagscan_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Tagscan_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['Tagscan_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'screen_id', name='uq_tagscan_role_permissions_role_screen')
    )
    op.create_table('Tagscan_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Tagscan_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Landing_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###

    # Module 1 now has real functionality — rename its tile from the
    # generic placeholder name to "Tagscan".
    op.execute('UPDATE "Landing_modules" SET name = \'Tagscan\' WHERE key = \'module-1\'')


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the placeholder name before dropping the tables that
    # required this rename in the first place.
    op.execute('UPDATE "Landing_modules" SET name = \'Module 1\' WHERE key = \'module-1\'')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tagscan_user_roles')
    op.drop_table('Tagscan_role_permissions')
    op.drop_index(op.f('ix_Tagscan_screens_key'), table_name='Tagscan_screens')
    op.drop_table('Tagscan_screens')
    op.drop_index(op.f('ix_Tagscan_roles_name'), table_name='Tagscan_roles')
    op.drop_table('Tagscan_roles')
    # ### end Alembic commands ###
