"""add kartracker tables

Revision ID: 3a5fbec6deb5
Revises: fdb0f1aaaf02
Create Date: 2026-09-08 16:23:19.928009

Auto-generated by Alembic from the four new KarTracker models (see
app/db/models/kartracker_*.py) — KarTracker's own custom-roles-with-per-
screen-permissions system, mirroring Tagscan's (module-1) and Intervention
Requests' (module-3). Also includes one hand-written data change: renaming
Module 2's display name to "KarTracker", now that it has real functionality
instead of being a placeholder (the seed script's seed_modules() only
fills in *missing* modules, so it wouldn't rename an already-existing row).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5fbec6deb5'
down_revision: Union[str, Sequence[str], None] = 'fdb0f1aaaf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KarTracker_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_roles_name'), 'KarTracker_roles', ['name'], unique=True)
    op.create_table('KarTracker_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_screens_key'), 'KarTracker_screens', ['key'], unique=True)
    op.create_table('KarTracker_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['KarTracker_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['KarTracker_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'screen_id', name='uq_kartracker_role_permissions_role_screen')
    )
    op.create_table('KarTracker_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['KarTracker_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Landing_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###

    # Module 2 now has real functionality — rename its tile from the
    # generic placeholder name to "KarTracker".
    op.execute('UPDATE "Landing_modules" SET name = \'KarTracker\' WHERE key = \'module-2\'')


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the placeholder name before dropping the tables that
    # required this rename in the first place.
    op.execute('UPDATE "Landing_modules" SET name = \'Module 2\' WHERE key = \'module-2\'')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KarTracker_user_roles')
    op.drop_table('KarTracker_role_permissions')
    op.drop_index(op.f('ix_KarTracker_screens_key'), table_name='KarTracker_screens')
    op.drop_table('KarTracker_screens')
    op.drop_index(op.f('ix_KarTracker_roles_name'), table_name='KarTracker_roles')
    op.drop_table('KarTracker_roles')
    # ### end Alembic commands ###
