"""add kartracker groundplan table

Revision ID: 41498ae1948d
Revises: 35e9d647d65f
Create Date: 2026-09-17 21:11:44.007405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41498ae1948d'
down_revision: Union[str, Sequence[str], None] = '35e9d647d65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KarTracker_groundplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_content_type', sa.String(length=100), nullable=True),
    sa.Column('sw_latitude', sa.Float(), nullable=True),
    sa.Column('sw_longitude', sa.Float(), nullable=True),
    sa.Column('ne_latitude', sa.Float(), nullable=True),
    sa.Column('ne_longitude', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KarTracker_groundplan')
    # ### end Alembic commands ###
