"""replace kartracker kar vereniging with team_id

Revision ID: 47a5bbcbeec2
Revises: b5790e98c92a
Create Date: 2026-09-09 21:51:05.502810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a5bbcbeec2'
down_revision: Union[str, Sequence[str], None] = 'b5790e98c92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('KarTracker_karren', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('KarTracker_karren_team_id_fkey', 'KarTracker_karren', 'MasterData_team', ['team_id'], ['id'])
    # ### end Alembic commands ###

    # Preserve every existing free-text "vereniging" value instead of just
    # discarding it: create a matching Team row for each distinct value
    # that doesn't already exist as a team (by name), then point each
    # kar's new team_id at the right team.
    connection = op.get_bind()
    distinct_names = connection.execute(
        sa.text('SELECT DISTINCT "vereniging" FROM "KarTracker_karren" WHERE "vereniging" IS NOT NULL')
    ).scalars().all()
    for name in distinct_names:
        connection.execute(
            sa.text('INSERT INTO "MasterData_team" (name) VALUES (:name) ON CONFLICT (name) DO NOTHING'),
            {"name": name},
        )
    connection.execute(
        sa.text(
            'UPDATE "KarTracker_karren" AS k SET team_id = t.id '
            'FROM "MasterData_team" AS t WHERE t.name = k."vereniging"'
        )
    )

    op.drop_column('KarTracker_karren', 'vereniging')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('KarTracker_karren', sa.Column('vereniging', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    # Restore "vereniging" from whichever team each kar ended up assigned
    # to, the mirror image of the backfill in upgrade() above.
    connection = op.get_bind()
    connection.execute(
        sa.text(
            'UPDATE "KarTracker_karren" AS k SET "vereniging" = t.name '
            'FROM "MasterData_team" AS t WHERE t.id = k.team_id'
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('KarTracker_karren_team_id_fkey', 'KarTracker_karren', type_='foreignkey')
    op.drop_column('KarTracker_karren', 'team_id')
    # ### end Alembic commands ###
