"""add tagscan rfid tag registry

Revision ID: 47e949e63597
Revises: 64680cd4b6f1
Create Date: 2026-09-01 19:51:39.205928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e949e63597'
down_revision: Union[str, Sequence[str], None] = '64680cd4b6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_rfid_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epc_uid', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_product_id', sa.Integer(), nullable=True),
    sa.Column('assigned_serial_number', sa.String(length=255), nullable=True),
    sa.Column('date_registered', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reader_id', sa.String(length=255), nullable=True),
    sa.Column('last_location', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=255), nullable=True),
    sa.Column('notes_1', sa.Text(), nullable=True),
    sa.Column('notes_2', sa.Text(), nullable=True),
    sa.Column('notes_3', sa.Text(), nullable=True),
    sa.Column('notes_4', sa.Text(), nullable=True),
    sa.Column('notes_5', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_product_id'], ['MasterData_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_rfid_tag_epc_uid'), 'Tagscan_rfid_tag', ['epc_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tagscan_rfid_tag_epc_uid'), table_name='Tagscan_rfid_tag')
    op.drop_table('Tagscan_rfid_tag')
    # ### end Alembic commands ###
