"""add masterdata product category lookup table

Revision ID: 64680cd4b6f1
Revises: 918cda824e7e
Create Date: 2026-08-31 20:32:17.025097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64680cd4b6f1'
down_revision: Union[str, Sequence[str], None] = '918cda824e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterData_product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_product_category_name'), 'MasterData_product_category', ['name'], unique=True)
    op.add_column('MasterData_product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'MasterData_product', 'MasterData_product_category', ['category_id'], ['id'])
    op.drop_column('MasterData_product', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MasterData_product', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'MasterData_product', type_='foreignkey')
    op.drop_column('MasterData_product', 'category_id')
    op.drop_index(op.f('ix_MasterData_product_category_name'), table_name='MasterData_product_category')
    op.drop_table('MasterData_product_category')
    # ### end Alembic commands ###
