"""add intervention requests roles and permissions tables

Revision ID: 7f9d4e32609d
Revises: 07dca593742e
Create Date: 2026-09-07 16:37:32.298587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9d4e32609d'
down_revision: Union[str, Sequence[str], None] = '07dca593742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InterventionRequests_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InterventionRequests_roles_name'), 'InterventionRequests_roles', ['name'], unique=True)
    op.create_table('InterventionRequests_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InterventionRequests_screens_key'), 'InterventionRequests_screens', ['key'], unique=True)
    op.create_table('InterventionRequests_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['InterventionRequests_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['InterventionRequests_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'screen_id', name='uq_interventionrequests_role_permissions_role_screen')
    )
    op.create_table('InterventionRequests_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['InterventionRequests_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Landing_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InterventionRequests_user_roles')
    op.drop_table('InterventionRequests_role_permissions')
    op.drop_index(op.f('ix_InterventionRequests_screens_key'), table_name='InterventionRequests_screens')
    op.drop_table('InterventionRequests_screens')
    op.drop_index(op.f('ix_InterventionRequests_roles_name'), table_name='InterventionRequests_roles')
    op.drop_table('InterventionRequests_roles')
    # ### end Alembic commands ###
