"""add masterdata product type warehouse limit lookup tables

Revision ID: 918cda824e7e
Revises: 2b4da56aaf09
Create Date: 2026-08-31 20:13:15.094689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918cda824e7e'
down_revision: Union[str, Sequence[str], None] = '2b4da56aaf09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterData_product_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_product_limit_name'), 'MasterData_product_limit', ['name'], unique=True)
    op.create_table('MasterData_product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_product_type_name'), 'MasterData_product_type', ['name'], unique=True)
    op.create_table('MasterData_warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MasterData_warehouse_name'), 'MasterData_warehouse', ['name'], unique=True)
    op.add_column('MasterData_product', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('MasterData_product', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('MasterData_product', sa.Column('limit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'MasterData_product', 'MasterData_product_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'MasterData_product', 'MasterData_warehouse', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'MasterData_product', 'MasterData_product_limit', ['limit_id'], ['id'])
    op.drop_column('MasterData_product', 'type')
    op.drop_column('MasterData_product', 'limit_mode')
    op.drop_column('MasterData_product', 'warehouse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MasterData_product', sa.Column('warehouse', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('MasterData_product', sa.Column('limit_mode', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('MasterData_product', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'MasterData_product', type_='foreignkey')
    op.drop_constraint(None, 'MasterData_product', type_='foreignkey')
    op.drop_constraint(None, 'MasterData_product', type_='foreignkey')
    op.drop_column('MasterData_product', 'limit_id')
    op.drop_column('MasterData_product', 'warehouse_id')
    op.drop_column('MasterData_product', 'type_id')
    op.drop_index(op.f('ix_MasterData_warehouse_name'), table_name='MasterData_warehouse')
    op.drop_table('MasterData_warehouse')
    op.drop_index(op.f('ix_MasterData_product_type_name'), table_name='MasterData_product_type')
    op.drop_table('MasterData_product_type')
    op.drop_index(op.f('ix_MasterData_product_limit_name'), table_name='MasterData_product_limit')
    op.drop_table('MasterData_product_limit')
    # ### end Alembic commands ###
