"""add active to festival

Revision ID: a857df14e361
Revises: 41498ae1948d
Create Date: 2026-09-19 20:07:58.093566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a857df14e361'
down_revision: Union[str, Sequence[str], None] = '41498ae1948d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MasterData_festival', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MasterData_festival', 'active')
    # ### end Alembic commands ###
