"""add kartracker kar management tables

Revision ID: b5790e98c92a
Revises: 3a5fbec6deb5
Create Date: 2026-09-09 20:56:42.302612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5790e98c92a'
down_revision: Union[str, Sequence[str], None] = '3a5fbec6deb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KarTracker_kar_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_kar_statuses_name'), 'KarTracker_kar_statuses', ['name'], unique=True)
    op.create_table('KarTracker_karren',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kar_nummer', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('vereniging', sa.String(length=255), nullable=True),
    sa.Column('transport_type_id', sa.Integer(), nullable=False),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['KarTracker_kar_statuses.id'], ),
    sa.ForeignKeyConstraint(['transport_type_id'], ['MasterData_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KarTracker_karren_kar_nummer'), 'KarTracker_karren', ['kar_nummer'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_KarTracker_karren_kar_nummer'), table_name='KarTracker_karren')
    op.drop_table('KarTracker_karren')
    op.drop_index(op.f('ix_KarTracker_kar_statuses_name'), table_name='KarTracker_kar_statuses')
    op.drop_table('KarTracker_kar_statuses')
    # ### end Alembic commands ###
