"""add tagscan header data log

Revision ID: d48867a8c01e
Revises: 47e949e63597
Create Date: 2026-09-02 17:59:56.165097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48867a8c01e'
down_revision: Union[str, Sequence[str], None] = '47e949e63597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_header_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_header_data_filename'), 'Tagscan_header_data', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tagscan_header_data_filename'), table_name='Tagscan_header_data')
    op.drop_table('Tagscan_header_data')
    # ### end Alembic commands ###
