"""add active to team

Revision ID: f0457ce24094
Revises: a857df14e361
Create Date: 2026-09-19 20:21:44.153629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0457ce24094'
down_revision: Union[str, Sequence[str], None] = 'a857df14e361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MasterData_team', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MasterData_team', 'active')
    # ### end Alembic commands ###
