"""add tagscan scanners table

Revision ID: f1ea3e98b1c9
Revises: f2b0799f5a01
Create Date: 2026-09-03 19:04:30.349690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ea3e98b1c9'
down_revision: Union[str, Sequence[str], None] = 'f2b0799f5a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_scanners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('info1', sa.Text(), nullable=True),
    sa.Column('info2', sa.Text(), nullable=True),
    sa.Column('info3', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['MasterData_product_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_scanners_scanner'), 'Tagscan_scanners', ['scanner'], unique=True)
    op.add_column('Tagscan_header_data', sa.Column('scanner', sa.String(length=255), nullable=True))
    op.add_column('Tagscan_header_data', sa.Column('scanner_id', sa.Integer(), nullable=True))
    op.add_column('Tagscan_header_data', sa.Column('scanner_name', sa.String(length=255), nullable=True))
    op.add_column('Tagscan_header_data', sa.Column('scanner_location', sa.Text(), nullable=True))
    op.add_column('Tagscan_header_data', sa.Column('scanner_technology', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'Tagscan_header_data', 'Tagscan_scanners', ['scanner_id'], ['id'])
    op.add_column('Tagscan_line_data', sa.Column('scanner_id', sa.Integer(), nullable=True))
    op.add_column('Tagscan_line_data', sa.Column('scanner_name', sa.String(length=255), nullable=True))
    op.add_column('Tagscan_line_data', sa.Column('scanner_location', sa.Text(), nullable=True))
    op.add_column('Tagscan_line_data', sa.Column('scanner_technology', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'Tagscan_line_data', 'Tagscan_scanners', ['scanner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tagscan_line_data', type_='foreignkey')
    op.drop_column('Tagscan_line_data', 'scanner_technology')
    op.drop_column('Tagscan_line_data', 'scanner_location')
    op.drop_column('Tagscan_line_data', 'scanner_name')
    op.drop_column('Tagscan_line_data', 'scanner_id')
    op.drop_constraint(None, 'Tagscan_header_data', type_='foreignkey')
    op.drop_column('Tagscan_header_data', 'scanner_technology')
    op.drop_column('Tagscan_header_data', 'scanner_location')
    op.drop_column('Tagscan_header_data', 'scanner_name')
    op.drop_column('Tagscan_header_data', 'scanner_id')
    op.drop_column('Tagscan_header_data', 'scanner')
    op.drop_index(op.f('ix_Tagscan_scanners_scanner'), table_name='Tagscan_scanners')
    op.drop_table('Tagscan_scanners')
    # ### end Alembic commands ###
