"""add tagscan line data log

Revision ID: f2b0799f5a01
Revises: d48867a8c01e
Create Date: 2026-09-02 18:51:42.049931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b0799f5a01'
down_revision: Union[str, Sequence[str], None] = 'd48867a8c01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tagscan_line_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_data_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=255), nullable=True),
    sa.Column('epc', sa.String(length=255), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('antenna', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('rfid_tag_id', sa.Integer(), nullable=True),
    sa.Column('assigned_product_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_serial_number', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['header_data_id'], ['Tagscan_header_data.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['Tagscan_rfid_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tagscan_line_data_epc'), 'Tagscan_line_data', ['epc'], unique=False)
    op.create_index(op.f('ix_Tagscan_line_data_header_data_id'), 'Tagscan_line_data', ['header_data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tagscan_line_data_header_data_id'), table_name='Tagscan_line_data')
    op.drop_index(op.f('ix_Tagscan_line_data_epc'), table_name='Tagscan_line_data')
    op.drop_table('Tagscan_line_data')
    # ### end Alembic commands ###
